#################################
##  DEV Configuration
#################################

# ===============================
#  Spring Cloud Config
# ===============================
spring.cloud.config.enabled: false 
spring.cloud.discovery.enabled: false
eureka.client.enabled: false

# ===============================
#  Basic Cofnig
# ===============================
# Server port
server.port: 8081

# Server Error never,on_trace_param,always
server.error: # Attention Required!!
  include-stacktrace: always 
  include-message: always 
  include-binding-errors: always 
  include-exception: false

# H2 Console
spring.h2.console.enabled: true # Attention Required!!
spring.h2.console.port: 0

# Open API Specification (Swagger 3)
springdoc.api-docs.enabled: true
springdoc.swagger-ui.enabled: true
springdoc.swagger-ui.filter: true


# Features
spring.liquibase.enabled: false

# ===============================
## Log Config
# ===============================
# Log Level 
logging.level:  # Attention Required!!
  th.go.dxc: DEBUG 
  org.springframework.web: DEBUG  
  org.springframework.ws.client.core.WebServiceTemplate: DEBUG
  org.springframework.ws.client.MessageTracing: DEBUG
  org.springframework.ws.server.MessageTracing: DEBUG
  org.springframework.ws.client.MessageTracing.sent: DEBUG
  org.springframework.ws.server.MessageTracing.sent: DEBUG
  org.springframework.ws.client.MessageTracing.received: DEBUG
  org.springframework.ws.server.MessageTracing.received: DEBUG
  sun.security: DEBUG

# Log File
logging.file.name: logs/${spring.application.name}-${spring.profiles.active}.log
logging.logback.rollingpolicy:
  file-name-pattern: logs/${spring.application.name}-${spring.profiles.active}-%d{yyyy-MM-dd}.%i.log
  max-file-size: 10MB
  max-history: 7
  total-size-cap: 0B
  clean-history-on-start: true # Attention Required!!
  
# ===============================
#  Spring Security Config
# ===============================
spring.security.oauth2.resourceserver:
  jwt:
    issuer-uri: https://sso.dxc.go.th/auth/realms/DXC

# ===============================
#  Application Cofig
# ===============================

# ThaID Api Connector
infra.connector.thaid:
   base_url: "https://imauth.bora.dopa.go.th"
   client_id: "d3E5WUNxNWZqQWtWWThOcmRGb3ZPSVVFMjFhOWRBM04"
   authorization: "Basic ZDNFNVdVTnhOV1pxUVd0V1dUaE9jbVJHYjNaUFNWVkZNakZoT1dSQk0wNDpTMngyTXpSdFUyNXdOMEZvZEhwWVFrTkZVVzFHT0VReU1HRnJWVlpQZG5oWmJYUXpSbXR1WWc="
   authorization_code: "authorization_code"
   refresh_token: "refresh_token"
   redirect_uri: "https://search.dxc.go.th/secured/v2/index.html#/loginThaiD"
   enable-wiretap: true  # ใช้ true เฉพาะ dev เพื่อ log request/response headers + body

# Dopa Linkage2 Api Connector
infra.connector.dopalinkage2:
   base_url: "http://10.14.33.9"
   
